<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Bixie\\Framework\\Console\\Commands\\TranslateCommand' => $vendorDir . '/bixie/framework/src/Console/Commands/TranslateCommand.php',
    'Bixie\\Framework\\FieldType\\FieldType' => $vendorDir . '/bixie/framework/src/FieldType/FieldType.php',
    'Bixie\\Framework\\FieldType\\FieldTypeBase' => $vendorDir . '/bixie/framework/src/FieldType/FieldTypeBase.php',
    'Bixie\\Framework\\FieldType\\FieldTypeInterface' => $vendorDir . '/bixie/framework/src/FieldType/FieldTypeInterface.php',
    'Bixie\\Framework\\FieldType\\FieldTypeUpload' => $vendorDir . '/bixie/framework/src/FieldType/FieldTypeUpload.php',
    'Bixie\\Framework\\FieldValue\\FieldValue' => $vendorDir . '/bixie/framework/src/FieldValue/FieldValue.php',
    'Bixie\\Framework\\FieldValue\\FieldValueBase' => $vendorDir . '/bixie/framework/src/FieldValue/FieldValueBase.php',
    'Bixie\\Framework\\FieldValue\\FieldValueInterface' => $vendorDir . '/bixie/framework/src/FieldValue/FieldValueInterface.php',
    'Bixie\\Framework\\Field\\FieldBase' => $vendorDir . '/bixie/framework/src/Field/FieldBase.php',
    'Bixie\\Framework\\Field\\FieldInterface' => $vendorDir . '/bixie/framework/src/Field/FieldInterface.php',
    'Bixie\\Framework\\Filter\\FileSizeFilter' => $vendorDir . '/bixie/framework/src/Filter/FileSizeFilter.php',
    'Bixie\\Framework\\FrameworkModule' => $vendorDir . '/bixie/framework/src/FrameworkModule.php',
    'Bixie\\Framework\\Traits\\CreatedModifiedTrait' => $vendorDir . '/bixie/framework/src/Traits/CreatedModifiedTrait.php',
    'Bixie\\Framework\\Traits\\JsonSerializableTrait' => $vendorDir . '/bixie/framework/src/Traits/JsonSerializableTrait.php',
    'ReCaptcha\\ReCaptcha' => $vendorDir . '/google/recaptcha/src/ReCaptcha/ReCaptcha.php',
    'ReCaptcha\\RequestMethod' => $vendorDir . '/google/recaptcha/src/ReCaptcha/RequestMethod.php',
    'ReCaptcha\\RequestMethod\\Curl' => $vendorDir . '/google/recaptcha/src/ReCaptcha/RequestMethod/Curl.php',
    'ReCaptcha\\RequestMethod\\CurlPost' => $vendorDir . '/google/recaptcha/src/ReCaptcha/RequestMethod/CurlPost.php',
    'ReCaptcha\\RequestMethod\\Post' => $vendorDir . '/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php',
    'ReCaptcha\\RequestMethod\\Socket' => $vendorDir . '/google/recaptcha/src/ReCaptcha/RequestMethod/Socket.php',
    'ReCaptcha\\RequestMethod\\SocketPost' => $vendorDir . '/google/recaptcha/src/ReCaptcha/RequestMethod/SocketPost.php',
    'ReCaptcha\\RequestParameters' => $vendorDir . '/google/recaptcha/src/ReCaptcha/RequestParameters.php',
    'ReCaptcha\\Response' => $vendorDir . '/google/recaptcha/src/ReCaptcha/Response.php',
    'abeautifulsite\\SimpleImage' => $vendorDir . '/abeautifulsite/simpleimage/src/abeautifulsite/SimpleImage.php',
);
